// ==UserScript==
// @name         Temu Product Link Exporter
// @namespace    http://tampermonkey.net/
// @version      0.5
// @description  Adds checkboxes to products on Temu category/search pages to select multiple items and export their links to a TXT file.
// @author       YourName (Generated by AI)
// @match        https://www.temu.com/*/*-*.*.html*
// @match        https://www.temu.com/search_result.html*
// @match        https://www.temu.com/categories/*
// @icon         https://www.google.com/s2/favicons?domain=temu.com
// @grant        GM_download
// @grant        GM_addStyle
// ==/UserScript==

(function() {
    'use strict';

    GM_addStyle(`
        .product-checkbox-container {
            display: inline-flex;
            align-items: center;
            margin-right: 8px; /* Adjust as needed */
            vertical-align: middle; /* Align with text/icons */
            cursor: pointer; /* Indicate it's clickable */
        }
        .product-checkbox {
            width: 18px; /* Adjust size as needed */
            height: 18px; /* Adjust size as needed */
            margin: 0;
        }
        /* Ensure the checkbox is clickable even if inside an <a> tag */
        .product-checkbox-container input[type="checkbox"] {
            pointer-events: auto;
        }

        #export-links-button {
            position: fixed;
            bottom: 20px;
            right: 20px;
            padding: 10px 15px;
            background-color: #007bff;
            color: white;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            z-index: 10000;
            font-size: 14px;
        }
    `);

    function addProductCheckboxes() {
        console.log("Attempting to add product checkboxes...");
        const productItems = document.querySelectorAll('a[href*="/goods_"]');
        let checkboxesAdded = 0;

        productItems.forEach(item => {
            if (item.querySelector('.product-checkbox-container')) {
                return;
            }

            const ratingContainer = item.querySelector('div._2aMrMQeS._1QhQr8pq div._3UEP91lE div.oMRVEXZ7._19DJKl1C');

            if (ratingContainer && ratingContainer.parentElement && ratingContainer.parentElement.parentElement) {
                const targetDivForCheckbox = ratingContainer.parentElement.parentElement;

                const checkboxContainer = document.createElement('div');
                checkboxContainer.className = 'product-checkbox-container';
                checkboxContainer.addEventListener('click', (e) => {
                    e.stopPropagation();
                    const chk = e.target.querySelector('.product-checkbox');
                    if(chk) chk.click();
                });

                const checkbox = document.createElement('input');
                checkbox.type = 'checkbox';
                checkbox.className = 'product-checkbox';
                checkbox.dataset.productUrl = item.href;

                checkbox.addEventListener('click', (e) => {
                    e.stopPropagation();
                });
                
                checkboxContainer.appendChild(checkbox);

                if (targetDivForCheckbox.parentNode) {
                     targetDivForCheckbox.parentNode.insertBefore(checkboxContainer, targetDivForCheckbox);
                     checkboxesAdded++;
                } else {
                    console.log("Could not find suitable parent for checkbox container for item:", item);
                }
            } else {
                 // console.log("Rating container not found for item:", item);
            }
        });
        if (checkboxesAdded > 0) {
            console.log(`Added ${checkboxesAdded} product checkboxes.`);
        } else {
            console.log("No new checkboxes added. Product items or rating containers might not be found or already processed. Check selectors.");
        }
    }

    function createExportButton() {
        console.log("Creating export button...");
        const exportButton = document.createElement('button');
        exportButton.id = 'export-links-button';
        exportButton.textContent = 'Export Selected Links';

        exportButton.addEventListener('click', () => {
            console.log('Export button clicked.');
            const checkedCheckboxes = document.querySelectorAll('input.product-checkbox:checked');
            const productLinks = [];

            checkedCheckboxes.forEach(checkbox => {
                if (checkbox.dataset.productUrl) {
                    productLinks.push(checkbox.dataset.productUrl);
                }
            });

            if (productLinks.length === 0) {
                alert('No products selected. Please check some products first.');
                console.log('No products selected for export.');
                return;
            }

            const linksText = productLinks.join('\n');
            const blob = new Blob([linksText], { type: 'text/plain' });
            const url = URL.createObjectURL(blob);

            console.log(`Exporting ${productLinks.length} links to temu_links.txt`);
            GM_download(url, 'temu_links.txt');

            // Clean up the object URL after a short delay
            setTimeout(() => {
                URL.revokeObjectURL(url);
                console.log('Object URL revoked.');
            }, 1000);
        });

        document.body.appendChild(exportButton);
        console.log("Export button added to page and export logic implemented.");
    }

    // Initial runs
    setTimeout(addProductCheckboxes, 2000); // Initial call for already loaded items
    createExportButton();

    // --- MutationObserver to handle dynamically loaded products ---
    const observerCallback = (mutationsList, observer) => {
        // We are only interested in added nodes
        let newNodesAdded = false;
        for (const mutation of mutationsList) {
            if (mutation.type === 'childList' && mutation.addedNodes.length > 0) {
                newNodesAdded = true;
                break;
            }
        }

        if (newNodesAdded) {
            console.log('DOM changed, running addProductCheckboxes again for new items.');
            // Call addProductCheckboxes after a short delay to allow new elements to be fully rendered
            setTimeout(addProductCheckboxes, 500);
        }
    };

    const observerConfig = {
        childList: true, // Observe direct children additions/removals
        subtree: true    // Observe all descendants of the target node
    };

    // Try to find a more specific target if possible.
    // Common selectors for main content areas: #content, #main, .main-content, [role="main"]
    // For Temu, a general product list area might be identifiable.
    // If not, document.body is the fallback.
    let targetNode = document.body; 
    // Example: A more specific (but potentially fragile) selector could be:
    // document.querySelector('div[class*="goods-list-container"]') || document.body;
    // The worker should attempt to find a reasonably stable container for product items.

    const observer = new MutationObserver(observerCallback);

    // Start observing the target node for configured mutations
    // Ensure the targetNode exists before observing
    if (targetNode) {
        observer.observe(targetNode, observerConfig);
        console.log('MutationObserver started to watch for new products.');
    } else {
        console.error('MutationObserver target node not found.');
    }

})();
